// optional-deps.ts — generates the publish artifacts from napi.targets.
// EVERYTHING comes from the SAME triples.ts: names, os, cpu, libc. No hand-written strings.
// This is what makes publish unable to diverge from build/loader.

import { resolveTriple, suffix, packageNameFor, type PlatformTriple } from "../core/triples.js";

/** package.json of a platform package (the one wrapping ONE .node) */
export interface PlatformPackageJson {
  name: string;
  version: string;
  os: string[];
  cpu: string[];
  libc?: string[];
  main: string;
  files: string[];
}

/**
 * Construye el package.json de un paquete de plataforma.
 * os/cpu/libc tell npm "don't even download this on the wrong platform".
 * El campo libc (npm 10+) es el equivalente declarativo de isMusl() del loader.
 */
export function platformPackageJson(
  base: string,
  crate: string,
  version: string,
  t: PlatformTriple
): PlatformPackageJson {
  const fileName = `${crate}.${suffix(t)}.node`; // SAME name build writes
  const pkg: PlatformPackageJson = {
    name: packageNameFor(base, t),
    version,
    os: [t.platform],
    cpu: [t.arch],
    main: fileName,
    files: [fileName],
  };
  // libc only applies on linux (gnu/musl); not included on windows/darwin
  if (t.abi === "musl" || t.abi === "gnu") {
    pkg.libc = [t.abi];
  }
  return pkg;
}

/**
 * Construye el bloque optionalDependencies para el package.json PRINCIPAL.
 * Pin EXACTO (no ^ ni ~): el binario nativo y el JS deben ir sincronizados
 * o se rompe el ABI. Este es el bug que casi todos cometen por costumbre.
 */
export function buildOptionalDeps(
  base: string,
  version: string,
  targets: string[]
): Record<string, string> {
  const deps: Record<string, string> = {};
  for (const triple of targets) {
    const t = resolveTriple(triple);
    deps[packageNameFor(base, t)] = version; // exact, no range
  }
  return deps;
}

/**
 * Shim de entrada del paquete PRINCIPAL.
 * El usuario hace `import { sum } from "@brashkie/hello-addon"` y esto carga
 * the correct per-platform .node via loadBinding, without knowing anything about loaders.
 * Generated as index.cjs for maximum .node loading compatibility.
 */
export function entryShim(crate: string, base: string): string {
  return `// AUTO-GENERATED by vekziun. Do not edit by hand.
const { loadBinding } = require("@vekziun/napi/loader");
const binding = loadBinding(${JSON.stringify(crate)}, ${JSON.stringify(base)}, __dirname);
module.exports = binding;
`;
}
